firstfile = open("Sample text.txt", "r")
secondfile = open("Test.txt", "r")
print("Sample text content:\n", firstfile.read())
print("Test content:\n", secondfile.read())
firstfile.close()
secondfile.close()
firstfile = open("Sample text.txt", "a+")
secondfile = open("Test.txt", "r")
firstfile.write(secondfile.read())
print("Updated Sample text content:\n", firstfile.read())
print("Test content:\n", secondfile.read())
firstfile.close()
secondfile.close()