f = open("Test.txt", "w")
f.write("Line 1\nLine 2\nLine 3\nLine 4\nLine 5\n")
f.close()
f = open("Test.txt", "r")
data = f.read()
print("Using read():\n", data)
f.close()
f = open("Test.txt", "r")
print("Using readline():\n", f.readline())
f.close()
f = open("Test.txt", "r")
lines = f.readlines()
print("Using readlines():\n", lines)
f.close()
f = open("Test.txt", "r")
lines = f.readlines()
print("Odd lines:")
for i in range(len(lines)):
    if i % 2 == 0:
        print(lines[i].strip())
f.close()
f = open("Test.txt", "a")
f.write("Line 6\nLine 7\n")
f.close()
f = open("Test.txt", "r")
print("After append:\n", f.read())
f.close()