file = open("Test.txt", "r")
print(file.read())
file.close()
file = open("Test.txt", "w")
file.write("This is a test file.")
file.close()
file = open("Test.txt", "a+")
file.write("\n This is a new line.")
file.close()