from tkinter import *
window = Tk()
window.title("Welcome to Sample Window")
window.geometry('350x300')
greeting = Label(window, text="Hello" , fg= 'blue' , bg='white')
button = Button(text="Click Me", fg='red', bg='yellow')
entry = Entry(fg='blue', bg='white')
greeting.pack()
button.pack()
entry.pack()
frame = Frame(master=window , relief=RAISED , borderwidth = 5)
frame.pack()
label = Label(master=frame , text="This is a Frame")
label.pack()
textbox = Text(fg= 'green' , bg = 'yellow' )
textbox.pack()
window.mainloop()